### PR TITLE
Updated plugin for cacti 1.x

### PR DESCRIPTION
**Pull request by Carlimeunier**
Update the plugin to make it operational on cacti 1.x

### CODE REVIEW

**Comment by cigamit** [comment]
Please check the current working develop version.  Browniebraun renamed all the cc_*.php files to *.php.  Sounds like this will really break things.  You need to rename and then see how much of a mess there is.  Sorry about that.  I won't close this, but there is definitely a lot of work to do.

**Comment by Carlimeunier** [comment]
I rename all cc _*.php files to *.php as it'is done in the repo.And I also modified all table's names, change lib_int directory to lib

**Comment by cigamit** [comment]
Carl, I have created a 'legacy' branch, can you move your pull request there?  Browniebraun asked me to ask you that.  We appreciate all your efforts.  Once you have created your pull there, I will merge strait away.

**Comment by cigamit** [comment]
Closing this one.  The other one will get merged.

**Pull request closed without merging**
