### PR TITLE
updated to be compatible with Cacti 1.x - Legacy branch

### PR DESCRIPTION
**Pull request by Carlimeunier**
This is an update to make the plugin reportit run on Cacti 1.x

### CODE REVIEW

**Comment by SergejLT** [comment]
what's the status with merging this? Is it working?

**Comment by ronytomen** [comment]
@Carlimeunier was looking at this pull request trying to figure out why it will not merge to the `legacy` branch...

Even on the command line, this PR against legacy is not merging cleanly.  Can make sure you do this work on the legacy branch? I noticed the PR was created from your `develop` branch, if you have been updating your develop branch, your PR request will not merge into the `legacy` branch.

**Comment by Carlimeunier** [comment]
Hello Rony,

Sorry for my late reply but I have been busy lately...

You're probably right because I did  a PR from my branch develop. So, I will fix that by creating the legacy branch in my repo and making a new PR.

I will get back to you with update asap.

**Comment by ronytomen** [comment]
Closing as new PR has been created.

**Pull request closed without merging**
